### ISSUE TITLE
Is it the CSS?

### ISSUE THREAD

**Issue by Ethsim12** [nottinghamtec/PyRIGS#603] opened 2024-10-27 15:05 UTC
Occasionally i press Rigs (the link in the top header of the forum), and it re-directs to the following;

![image](https://github.com/user-attachments/assets/57c60608-cbb5-422a-befc-c6896bc51c41)

I then press "Done" because it's a safari pop-up from forum that has forum home screen icon. On second attempt, usually the styling is then as it should be;

![image](https://github.com/user-attachments/assets/becf22f5-d9db-4e4e-9d4a-de9241fe56ce)

**Comment by jb3** [comment] 2024-10-29 21:45
This is likely just transient network conditions and isn't something we can really mitigate.

If it's something that resolves after a second attempt I'm not sure if much else can be done here about a FOUC or transient network condition. The JavaScript to try mitigate and detect this is overkill compared to people just realising and reloading their browsers.

**Comment by jb3** [comment] 2024-11-01 21:43
Since this isn't something that's really resolvable, or even detectable (if the CSS has failed to load I'm not holding out hopes for the JS), I'm going to close this one out for now.

If this becomes persistent or reproducible then feel free to post here again/create a new issue but for now this isn't something to address.

**Closed as not planned by jb3** 2024-11-01 21:43 UTC
